### ISSUE TITLE
Add cf_role to the attributes of the 'id' dimension

### ISSUE THREAD

**Issue by RondeauG** [hydrologie/xdatasets#29]
To follow CF Conventions, discrete datasets with a `station` dimension (no standardized name, so `id` works too) should have a `cf_role` attribute with a value `"timeseries_id"`. This is what allows the right dimension to be easily identified, similarly to the `axis` attribute for `lon/lat`.

http://cfconventions.org/cf-conventions/cf-conventions.html#time-series-data

> It is strongly recommended that there should be a station variable (which may be of any type) with the attribute cf_role=”timeseries_id”, whose values uniquely identify the stations.

**Comment by sebastienlanglois** [comment]
Yes, I will add this to the DEH dataset and any other dataset further on.

On a site note, I think that after the change is made, we should keep the documentation mentioning the cf_role attribute in xhydro's documentation so that users are aware of this if they decide to provide their own datasets
