### ISSUE TITLE
Enable Trusted Publishing

### ISSUE THREAD

**Issue by Zeitsperre** [hydrologie/xdatasets#34]
The new GitHub Actions now allow for tokenless publishing: https://docs.pypi.org/trusted-publishers/using-a-publisher/

There are a handful of configurations to be made in TestPyPI and PyPI.

@sebastienlanglois 
If you're comfortable extending "Owner" access to me at both of those indexes, I can set this up; Otherwise, I can give you a rundown of what exactly needs to be done. Probably around 5 to 10 minutes of configuring.

Let me know!

**Comment by sebastienlanglois** [comment]
@Zeitsperre 
I just changed your profile to Owner for both TestPyPi et PyPI!

**Comment by Zeitsperre** [comment]
Awesome. Trusted Publishing is now in place!
