### ISSUE TITLE
Rename `master` to `main` branch

### ISSUE THREAD

**Issue by Zeitsperre** [hydrologie/xdatasets#60]
### Generic Issue

The new convention for GitHub repositories is to move from `master` to `main` (https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/). The cookiecutter workflows expect a `main` branch as well.

There hasn't been much action going on here, so given that fact, I propose that once the Dependabot Pull Requests have been merged, we rename the trunk to `main`.

@RondeauG @sebastienlanglois any opposition?

**Comment by RondeauG** [comment]
Pas de problème pour moi !

**Comment by sebastienlanglois** [comment]
Sounds good to me!

**Comment by Zeitsperre** [comment]
Done.
