### ISSUE TITLE
Catalogs might not be compatible with `intake >2.0.0`

### ISSUE THREAD

**Issue by RondeauG** [hydrologie/xdatasets#82]
### Setup Information

- xdatasets version: 0.3.4
- Python version: 3.11.8
- Operating System: Windows

### Description

See https://github.com/hydrologie/xhydro/issues/105. Newer versions of `intake` raise an error when trying to read the YAML catalogs. Versions tested are 2.0.1 and 2.0.3.

At minimum, the upper bound of `intake` should be pinned for the time being.

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by sebastienlanglois** [comment]
Thanks @RondeauG. Yes indeed there are quite a few changes happening with Intake 2. 
I will adapt xdatasets's catalogs for intake 2.

In the meantime, I suggest that we limit intake < 2 in xhydro's dependencies.

**Comment by Zeitsperre** [comment]
@sebastienlanglois 

If I could propose an approach for the intermediate: Can we release a version of `xdatasets` with this upper pin for now? We can revert this change this when your Pull Request is ready.
